"""update2 relationships

Revision ID: 991e938f20e5
Revises: ff480872b68b
Create Date: 2024-04-16 02:16:56.924254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991e938f20e5'
down_revision = 'ff480872b68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_suites_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_suites_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
