"""update relationship

Revision ID: ff480872b68b
Revises: 14bffc8acf52
Create Date: 2024-04-15 12:49:11.729518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff480872b68b'
down_revision = '14bffc8acf52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suite_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tenants_suite_id_suites'), 'suites', ['suite_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tenants_suite_id_suites'), type_='foreignkey')
        batch_op.drop_column('suite_id')

    # ### end Alembic commands ###
